mysql:
  db: chatnio
  host: 10.11.111.62
  password: hzmu7fGW
  port: 3306
  user: root

redis:
  host: localhost
  port: 6379
  db: 0
  password: ""


secret: secret
serve_static: true

server:
  port: 80
system:
  general:
    backend: ""
  mail:
    host: ""
    port: 465
    username: ""
    password: ""
    from: ""
  search:
    endpoint: https://duckduckgo-api.vercel.app
    query: 5

